### ISSUE TITLE
No graphs from kippo

### ISSUE THREAD

**Issue by lambis7** [mercolino/mhn_kippo_graphs#7]
Hi,

i succesfully installed mhn_kippo_graphs to MHN Server, i deployed the modified script in order to install kippo with MySQL support on raspberry pi 3 but  i do not get the graphs. They are empty despite the attacks. 

How can i solve this?

**Comment by lambis7** [comment]
@mercolino When i try to manually execute the script 'kippo_generate_graphs.py' as 
'python3 kippo_generate_graphs.py'  i get the error above:

  File "kippo_generate_graphs.py", line 26
    print 'No enough data to generate the graph %s but no file generated because PIL Library was not found' % name
                                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'

and when i manually execute the script as 'python kippo_generate_graphs.py' i get the error above:
Traceback (most recent call last):
  File "kippo_generate_graphs.py", line 2, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot


How can i fix that?

[EDIT]
I installed sudo apt-get install python3-pip python3-matplotlib & sudo pip3 install PyMySQL and i no longer get the previous errors. But when i execute the script with python3 i get the errors above:

Traceback (most recent call last):
  File "kippo_generate_graphs.py", line 675, in <module>
    main()
  File "kippo_generate_graphs.py", line 653, in main
    generateTop10Passwords(db)
  File "kippo_generate_graphs.py", line 115, in generateTop10Passwords
    cur.execute(sql)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 835, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1019, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 1302, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 981, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.4/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.4/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'kippo_2227168a_c4aa_11e6_86fb_aa0cfad5293e.auth' doesn't exist")
